version: 1
disable_existing_loggers: false
formatters:
  default:
    format: "%(asctime)s %(levelname)s %(name)s: %(message)s"
handlers:
  file:
    class: logging.FileHandler
    filename: logs/web.log
    formatter: default
  console:
    class: logging.StreamHandler
    formatter: default
loggers:
  uvicorn:
    handlers: [file, console]
    level: INFO
    propagate: false
  uvicorn.error:
    handlers: [file, console]
    level: INFO
    propagate: false
  uvicorn.access:
    handlers: [file, console]
    level: INFO
    propagate: false
root:
  handlers: [file, console]
  level: INFO